# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.proto import zakon_pb2 as src_dot_proto_dot_zakon__pb2


class ZakonCrawlerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetShortNews = channel.unary_unary(
                '/ZakonCrawler/GetShortNews',
                request_serializer=src_dot_proto_dot_zakon__pb2.ShortNewsRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_zakon__pb2.ShortNewsResponse.FromString,
                )
        self.GetFullNews = channel.unary_unary(
                '/ZakonCrawler/GetFullNews',
                request_serializer=src_dot_proto_dot_zakon__pb2.FullNewsRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_zakon__pb2.FullNewsResponse.FromString,
                )


class ZakonCrawlerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetShortNews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFullNews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ZakonCrawlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetShortNews': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShortNews,
                    request_deserializer=src_dot_proto_dot_zakon__pb2.ShortNewsRequest.FromString,
                    response_serializer=src_dot_proto_dot_zakon__pb2.ShortNewsResponse.SerializeToString,
            ),
            'GetFullNews': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFullNews,
                    request_deserializer=src_dot_proto_dot_zakon__pb2.FullNewsRequest.FromString,
                    response_serializer=src_dot_proto_dot_zakon__pb2.FullNewsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ZakonCrawler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ZakonCrawler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetShortNews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ZakonCrawler/GetShortNews',
            src_dot_proto_dot_zakon__pb2.ShortNewsRequest.SerializeToString,
            src_dot_proto_dot_zakon__pb2.ShortNewsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFullNews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ZakonCrawler/GetFullNews',
            src_dot_proto_dot_zakon__pb2.FullNewsRequest.SerializeToString,
            src_dot_proto_dot_zakon__pb2.FullNewsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
