# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/zakon.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/proto/zakon.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15src/proto/zakon.proto\"0\n\x10ShortNewsRequest\x12\x12\n\x05\x63ount\x18\x01 \x01(\x05H\x00\x88\x01\x01\x42\x08\n\x06_count\"-\n\x11ShortNewsResponse\x12\x18\n\x04news\x18\x01 \x03(\x0b\x32\n.ShortNews\"(\n\tShortNews\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\"/\n\x0f\x46ullNewsRequest\x12\x12\n\x05\x63ount\x18\x01 \x01(\x05H\x00\x88\x01\x01\x42\x08\n\x06_count\"+\n\x10\x46ullNewsResponse\x12\x17\n\x04news\x18\x01 \x03(\x0b\x32\t.FullNews\"`\n\x08\x46ullNews\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\tfull_text\x18\x03 \x01(\t\x12\x12\n\nimage_link\x18\x04 \x01(\t\x12\x11\n\tnews_date\x18\x05 \x01(\t2}\n\x0cZakonCrawler\x12\x37\n\x0cGetShortNews\x12\x11.ShortNewsRequest\x1a\x12.ShortNewsResponse\"\x00\x12\x34\n\x0bGetFullNews\x12\x10.FullNewsRequest\x1a\x11.FullNewsResponse\"\x00\x62\x06proto3'
)




_SHORTNEWSREQUEST = _descriptor.Descriptor(
  name='ShortNewsRequest',
  full_name='ShortNewsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='ShortNewsRequest.count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_count', full_name='ShortNewsRequest._count',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=25,
  serialized_end=73,
)


_SHORTNEWSRESPONSE = _descriptor.Descriptor(
  name='ShortNewsResponse',
  full_name='ShortNewsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='news', full_name='ShortNewsResponse.news', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=120,
)


_SHORTNEWS = _descriptor.Descriptor(
  name='ShortNews',
  full_name='ShortNews',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='ShortNews.time', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='ShortNews.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=162,
)


_FULLNEWSREQUEST = _descriptor.Descriptor(
  name='FullNewsRequest',
  full_name='FullNewsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='FullNewsRequest.count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_count', full_name='FullNewsRequest._count',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=164,
  serialized_end=211,
)


_FULLNEWSRESPONSE = _descriptor.Descriptor(
  name='FullNewsResponse',
  full_name='FullNewsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='news', full_name='FullNewsResponse.news', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=256,
)


_FULLNEWS = _descriptor.Descriptor(
  name='FullNews',
  full_name='FullNews',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='FullNews.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='FullNews.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='full_text', full_name='FullNews.full_text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image_link', full_name='FullNews.image_link', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='news_date', full_name='FullNews.news_date', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=354,
)

_SHORTNEWSREQUEST.oneofs_by_name['_count'].fields.append(
  _SHORTNEWSREQUEST.fields_by_name['count'])
_SHORTNEWSREQUEST.fields_by_name['count'].containing_oneof = _SHORTNEWSREQUEST.oneofs_by_name['_count']
_SHORTNEWSRESPONSE.fields_by_name['news'].message_type = _SHORTNEWS
_FULLNEWSREQUEST.oneofs_by_name['_count'].fields.append(
  _FULLNEWSREQUEST.fields_by_name['count'])
_FULLNEWSREQUEST.fields_by_name['count'].containing_oneof = _FULLNEWSREQUEST.oneofs_by_name['_count']
_FULLNEWSRESPONSE.fields_by_name['news'].message_type = _FULLNEWS
DESCRIPTOR.message_types_by_name['ShortNewsRequest'] = _SHORTNEWSREQUEST
DESCRIPTOR.message_types_by_name['ShortNewsResponse'] = _SHORTNEWSRESPONSE
DESCRIPTOR.message_types_by_name['ShortNews'] = _SHORTNEWS
DESCRIPTOR.message_types_by_name['FullNewsRequest'] = _FULLNEWSREQUEST
DESCRIPTOR.message_types_by_name['FullNewsResponse'] = _FULLNEWSRESPONSE
DESCRIPTOR.message_types_by_name['FullNews'] = _FULLNEWS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ShortNewsRequest = _reflection.GeneratedProtocolMessageType('ShortNewsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHORTNEWSREQUEST,
  '__module__' : 'src.proto.zakon_pb2'
  # @@protoc_insertion_point(class_scope:ShortNewsRequest)
  })
_sym_db.RegisterMessage(ShortNewsRequest)

ShortNewsResponse = _reflection.GeneratedProtocolMessageType('ShortNewsResponse', (_message.Message,), {
  'DESCRIPTOR' : _SHORTNEWSRESPONSE,
  '__module__' : 'src.proto.zakon_pb2'
  # @@protoc_insertion_point(class_scope:ShortNewsResponse)
  })
_sym_db.RegisterMessage(ShortNewsResponse)

ShortNews = _reflection.GeneratedProtocolMessageType('ShortNews', (_message.Message,), {
  'DESCRIPTOR' : _SHORTNEWS,
  '__module__' : 'src.proto.zakon_pb2'
  # @@protoc_insertion_point(class_scope:ShortNews)
  })
_sym_db.RegisterMessage(ShortNews)

FullNewsRequest = _reflection.GeneratedProtocolMessageType('FullNewsRequest', (_message.Message,), {
  'DESCRIPTOR' : _FULLNEWSREQUEST,
  '__module__' : 'src.proto.zakon_pb2'
  # @@protoc_insertion_point(class_scope:FullNewsRequest)
  })
_sym_db.RegisterMessage(FullNewsRequest)

FullNewsResponse = _reflection.GeneratedProtocolMessageType('FullNewsResponse', (_message.Message,), {
  'DESCRIPTOR' : _FULLNEWSRESPONSE,
  '__module__' : 'src.proto.zakon_pb2'
  # @@protoc_insertion_point(class_scope:FullNewsResponse)
  })
_sym_db.RegisterMessage(FullNewsResponse)

FullNews = _reflection.GeneratedProtocolMessageType('FullNews', (_message.Message,), {
  'DESCRIPTOR' : _FULLNEWS,
  '__module__' : 'src.proto.zakon_pb2'
  # @@protoc_insertion_point(class_scope:FullNews)
  })
_sym_db.RegisterMessage(FullNews)



_ZAKONCRAWLER = _descriptor.ServiceDescriptor(
  name='ZakonCrawler',
  full_name='ZakonCrawler',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=356,
  serialized_end=481,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetShortNews',
    full_name='ZakonCrawler.GetShortNews',
    index=0,
    containing_service=None,
    input_type=_SHORTNEWSREQUEST,
    output_type=_SHORTNEWSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetFullNews',
    full_name='ZakonCrawler.GetFullNews',
    index=1,
    containing_service=None,
    input_type=_FULLNEWSREQUEST,
    output_type=_FULLNEWSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ZAKONCRAWLER)

DESCRIPTOR.services_by_name['ZakonCrawler'] = _ZAKONCRAWLER

# @@protoc_insertion_point(module_scope)
